#!/bin/bash

branches=$(git branch --merged ${1-master} | grep -v " ${1-master}$")

if [ ! -z "${branches}" ]; then
  for branch in ${branches}; do
    git branch -d ${branch}
  done
else
  echo "No branches to cleanup"
fi
